services:
  gluetun:
    image: qmcgaw/gluetun:latest
    hostname: gluetun
    cap_add:
      - NET_ADMIN
    env_file:
      - path: ./conf/gluetun.env
    environment:
      - OPENVPN_CUSTOM_CONFIG="/gluetun/custom.conf"
    volumes:
      - ./conf/vpn.ovpn:/gluetun/custom.conf:ro
    restart: always

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    env_file:
      - path: ./conf/common.env
    environment:
      - WEBUI_PORT=5080
    volumes:
      - /opt/media/qbittorrent/appdata/config:/config
      - /mnt/game0/media/downloads:/new
    network_mode: service:gluetun
    restart: always

  jellyfin:
    image: jellyfin/jellyfin:latest
    hostname: jellyfin
    user: 972:962
    env_file:
      - path: ./conf/common.env
    volumes:
      - /opt/media/jellyfin/config:/config
      - /opt/media/jellyfin/cache:/cache
      - /mnt/game0/media:/media
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/kfd:/dev/kfd
    environment:
      - ROC_ENABLE_PRE_VEGA=1
      #- DOCKER_MODS=linuxserver/mods:jellyfin-amd
    restart: always

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    hostname: radarr
    env_file:
      - path: ./conf/common.env
    volumes:
      - /opt/media/radarr:/config
      - /mnt/game0/media/movies:/downloads
      - /mnt/game0/media/downloads:/new
    restart: always

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    hostname: sonarr
    env_file:
      - path: ./conf/common.env
    volumes:
      - /opt/media/sonarr:/config
      - /mnt/game0/media/shows:/downloads
      - /mnt/game0/media/downloads:/new
    restart: always
    # calibre:
    # image: ghcr.io/linuxserver/calibre:latest
    # env_file:
    # - path: ./conf/common.env
    # volumes:
    # - /opt/media/calibre/config:/config
    # - /opt/media/calibre/plugins:/plugins
    # - /opt/media/downloads:/uploads
    # - /mnt/game0/media/books:/Calibre_Library
    # restart: always
    #
    # calibre-web:
    # image: ghcr.io/linuxserver/calibre-web:latest
    # env_file:
    # - path: ./conf/common.env
    # volumes:
    # - /opt/media/calibre-web:/config
    # - /mnt/game0/media/books:/books
    # restart: always
    # depends_on:
    # - calibre

    # readarr:
    #   image: lscr.io/linuxserver/readarr:develop
    #   env_file: ./conf/common.env
    #   volumes:
    #     - /opt/media/readarr:/config
    #     - /mnt/game0/media/books:/downloads
    #     - /mnt/game0/media/downloads:/new
    #   restart: always

  prowlarr:
    image: linuxserver/prowlarr:latest
    hostname: prowlarr
    env_file:
      - path: ./conf/common.env
    volumes:
      - /opt/media/prowlarr:/config
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    env_file:
      - path: ./conf/common.env
    environment:
      LOG_LEVEL: info
    network_mode: service:gluetun
    restart: always

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    hostname: jellyseerr
    env_file:
      - path: ./conf/common.env
    volumes:
      - /opt/media/jellyseerr:/app/config
    restart: unless-stopped

  nginx:
    image: nginx:1.25.1-alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./www:/var/www:ro
    ports:
      - 80:80
    restart: unless-stopped

  rathole:
    image: rapiz1/rathole
    hostname: rathole
    command: "--client /app/config.toml"
    volumes:
      - ./conf/rathole.toml:/app/config.toml
    restart: unless-stopped
